---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Ubuntu
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates for Fedora
    ansible.builtin.yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora" 

- hosts: web_servers
  become: true
  tasks:

  - name: install apache on web servers
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install MariaDB on db servers
    ansible.builtin.yum:
      name: mariadb
      state: latest 
    when: ansible_distribution == "Fedora"


