---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates for Fedora
    tags: always
    ansible.builtin.yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora" 

- hosts: web_servers
  become: true
  tasks:

  - name: install apache on web servers (Ubunut)
    tags: apache, ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

  - name: install apache on web servers (Fedora)
    tags: apache, fedora
    ansible.builtin.yum:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: ensure apache is running (Ubuntu)
    tags: apache, ubnutu
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"    

  - name: ensure apache is running (Fedora)
    tags: apache, fedora
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_distribution == "Fedora"    

  - name: change email address for admin
    tags: apache, fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin myemail@example.net       
    when: ansible_distribution == "Fedora"    
    register: httpd

  - name: restart httpd (Fedora)
    tags: apache, fedora
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: httpd.changed    
    
  - name: copy html file for site
    tags: apache, ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

- hosts: db_servers
  become: true
  tasks:

  - name: install MariaDB on db servers
    tags: db, fedora
    ansible.builtin.yum:
      name: mariadb
      state: latest 
    when: ansible_distribution == "Fedora"


